esphome:
  name: office-ble-presence

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging to help troubleshoot and find Bluetooth device information.
#   "VERY_VERBOSE" should probably be used in most situations these days as Bluetooth 
#     MAC address randomization means you will likely be relying upon service UUIDs which  
#     don't show up using the "VERBOSE" logging level.
#   "VERBOSE" level is useful to see older Bluetooth devices that don't use 
#     randomized MAC addresses so you can create automations using Bluetooth MAC addresses.  
logger: 
  level: VERY_VERBOSE       
  
# Enable Home Assistant API.
api:
  encryption:
    key: "PleaseChangeMe"

ota:
  password: "PleaseChangeMe"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
# If you want your sensor to use a static IP on your network, un-comment and update the block below:
#    manual_ip:
#      static_ip: PleaseChangeMe
#      gateway: PleaseChangeMe
#      subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails.
  ap:
    ssid: "PleaseChangeMe"
    password: "PleaseChangeMe"

captive_portal:
    
esp32_ble_tracker:

# Once you find your device's service UUID, iBeacon UUID, or MAC address, use the templates 
#   below to help you identify your devices within Home Assistant.
# NOTE: do NOT use anything with an address type of 'RANDOM' as those address types are useless.
binary_sensor:
  - platform: ble_presence
    service_uuid: 'FEFF'
    name: "Jabra Elite 85h"  # How this will display in Home Assistant.
  
  - platform: ble_presence
    service_uuid: '180D'
    name: "TICKR 59A1 HRM"  # How this will display in Home Assistant.

  - platform: ble_presence
    service_uuid: 'FDD2'
    name: "Bose 700 UC"  # How this will display in Home Assistant.

  # Example of presence based on MAC address
  #- platform: ble_presence
  #  mac_address: xx:xx:xx:x:xx:xx
  #  name: "Jabra Elite 85h"

  # Example of presence based on iBeacon UUID
  #- platform: ble_presence
    #ibeacon_uuid: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
    #name: "Jabra Elite 85h"

